import "./globals.css";
import { ThemeProvider } from './components/theme.js';

// Assuming you are using Inter font from Google Fonts elsewhere,
// you might want to include it in your CSS file or link it in your HTML head.

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <head>
          {/* Include Inter font here if needed */}
        </head>
        <body>{children}</body>
      </html>
    </ThemeProvider>
  );
}
